--1.1 Создать таблицу employees.
create table employees (
	id serial primary key,
	employees_name varchar(50) not null);

--1.2 Наполнить таблицу employee 70 строками.
insert into employees (employees_name)
values ('Kevin Wright'),
	   ('Franco Hernandez'),
	   ('Matthew Bell'),
	   ('Charles Walker'),
	   ('Emiliano Barnes'),
	   ('Xavier Brown'),
	   ('Irvin Mitchell'),
	   ('Harlow Mitchell'),
	   ('Trenton Thompson'),
	   ('Hudson Taylor'),
	   ('Yitzchak Butler'),
	   ('Gunnar Griffin'),
	   ('Quang Parker'),
	   ('Xathieur Hughes'),
	   ('Atlas Martinez'),
	   ('Marshall Adams'),
	   ('Grant Cooper'),
	   ('Keith Lopez'),
	   ('Oscar Martin'),
	   ('Holland Rodriguez'),
	   ('Kyler Foster'),
	   ('Owen Perez'),
	   ('Neil Evans'),
	   ('Dax Powell'),
	   ('Duke Morgan'),
	   ('Umer Thomas'),
	   ('Omar Barnes'),
	   ('Arlo Lee'),
	   ('Yusef Hughes'),
	   ('Emmitt Bryant'),
	   ('Lukas Richardson'),
	   ('Louis Rogers'),
	   ('Remington Harris'),
	   ('Kyler Peterson'),
	   ('Bruno Rivera'),
	   ('Eleanor Alexander'),
	   ('Miranda Williams'),
	   ('Brisa Garcia'),
	   ('Demi Lopez'),
	   ('Ursala Kelly'),
	   ('Demi Baker'),
	   ('Jayda Jones'),
	   ('Yelena Parker'),
	   ('Nicole Washington'),
	   ('Quella Moore'),
	   ('Ophelia Simmons'),
	   ('Elisa White'),
	   ('Octavie Watson'),
	   ('Emilia Evans'),
	   ('Nia Allen'),
	   ('Yvonne Gonzalez'),
	   ('Jazmine Edwards'),
	   ('Gracelynn Bell'),
	   ('Kaylee Bailey'),
	   ('Greta Ward'),
	   ('Zinnia Perez'),
	   ('Winnifred Brown'),
	   ('Fatima Gonzales'),
	   ('Luna Bennett'),
	   ('Jayla Harris'),
	   ('Leila Rodriguez'),
	   ('Noa Evans'),
	   ('Yulianna Watson'),
	   ('Rosalyn Rodriguez'),
	   ('Isabella Flores'),
	   ('Yadira Foster'),
	   ('Rosemary Griffin'),
	   ('Tabitha Campbell'),
	   ('Charli Edwards'),
	   ('Emelia Scott');
	  
select * from employees e;
